In [108]:
import pandas as pd

In [109]:
restaurants = pd.read_csv('../data/TA_restaurants.csv')

In [110]:
restaurants.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125527 entries, 0 to 125526
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         125527 non-null  int64
 1   Name               125527 non-null  object
 2   City               125527 non-null  object
 3   Cuisine Style      94176 non-null   object
 4   Ranking            115876 non-null  float64
 5   Rating             115897 non-null  float64
 6   Price Range        77672 non-null   object
 7   Number of Reviews  108183 non-null  float64
 8   Reviews            115911 non-null  object
 9   URL_TA             125527 non-null  object
 10  ID_TA              125527 non-null  object
dtypes: float64(3), int64(1), object(7)
memory usage: 10.5+ MB

In [111]:
restaurants.shape

(125527, 11)

In [112]:
restaurants.head()

,Unnamed: 0,Name,City,Cuisine Style,Ranking,Rating,Price Range,Number of Reviews,Reviews,URL_TA,ID_TA
0,0,Martine of Martine's Table,Amsterdam,"['French', 'Dutch', 'European']",1.0,5.0,$$ - $$$,136.0,"[['Just like home', 'A Warm Welcome to Wintry ...",/Restaurant_Review-g188590-d11752080-Reviews-M...,d11752080
1,1,De Silveren Spiegel,Amsterdam,"['Dutch', 'European', 'Vegetarian Friendly', '...",2.0,4.5,$$$$,812.0,"[['Great food and staff', 'just perfect'], ['0...",/Restaurant_Review-g188590-d693419-Reviews-De_...,d693419
2,2,La Rive,Amsterdam,"['Mediterranean', 'French', 'International', '...",3.0,4.5,$$$$,567.0,"[['Satisfaction', 'Delicious old school restau...",/Restaurant_Review-g188590-d696959-Reviews-La_...,d696959
3,3,Vinkeles,Amsterdam,"['French', 'European', 'International', 'Conte...",4.0,5.0,$$$$,564.0,"[['True five star dinner', 'A superb evening o...",/Restaurant_Review-g188590-d1239229-Reviews-Vi...,d1239229
4,4,Librije's Zusje Amsterdam,Amsterdam,"['Dutch', 'European', 'International', 'Vegeta...",5.0,4.5,$$$$,316.0,"[['Best meal.... EVER', 'super food experience...",/Restaurant_Review-g188590-d6864170-Reviews-Li...,d6864170

In [154]:
list(restaurants.City.unique())

['Amsterdam',
 'Athens',
 'Barcelona',
 'Berlin',
 'Bratislava',
 'Brussels',
 'Budapest',
 'Copenhagen',
 'Dublin',
 'Edinburgh',
 'Geneva',
 'Hamburg',
 'Helsinki',
 'Krakow',
 'Lisbon',
 'Ljubljana',
 'London',
 'Luxembourg',
 'Lyon',
 'Madrid',
 'Milan',
 'Munich',
 'Oporto',
 'Oslo',
 'Paris',
 'Prague',
 'Rome',
 'Stockholm',
 'Vienna',
 'Warsaw',
 'Zurich']

In [114]:
restaurants = restaurants.dropna()

In [115]:
restaurants['Reviews'][67379]

"[['Absolutely divine tastes and flavours', 'Loved it'], ['01/09/2018', '01/07/2018']]"

In [116]:
for i in range(0, 11):
    if 'Dutch' in restaurants['Cuisine Style'][i]:
        print(True)
    else:
        print(False)

True
True
False
False
True
False
False
False
False
True
False

In [117]:
if 'Dutch' in restaurants['Cuisine Style'][0]:
    print(True)

True

In [118]:
restaurants['Cuisine Style']

0                           ['French', 'Dutch', 'European']
1         ['Dutch', 'European', 'Vegetarian Friendly', '...
2         ['Mediterranean', 'French', 'International', '...
3         ['French', 'European', 'International', 'Conte...
4         ['Dutch', 'European', 'International', 'Vegeta...
                                ...
125423    ['Indian', 'Asian', 'Vegetarian Friendly', 'Ha...
125434    ['Mediterranean', 'European', 'Central Europea...
125435                                              ['Bar']
125438    ['Chinese', 'Swiss', 'Mediterranean', 'European']
125445                   ['Italian', 'Vegetarian Friendly']
Name: Cuisine Style, Length: 74225, dtype: object

In [119]:
restaurants['Cuisine Style'].value_counts

<bound method IndexOpsMixin.value_counts of 0                           ['French', 'Dutch', 'European']
1         ['Dutch', 'European', 'Vegetarian Friendly', '...
2         ['Mediterranean', 'French', 'International', '...
3         ['French', 'European', 'International', 'Conte...
4         ['Dutch', 'European', 'International', 'Vegeta...
                                ...
125423    ['Indian', 'Asian', 'Vegetarian Friendly', 'Ha...
125434    ['Mediterranean', 'European', 'Central Europea...
125435                                              ['Bar']
125438    ['Chinese', 'Swiss', 'Mediterranean', 'European']
125445                   ['Italian', 'Vegetarian Friendly']
Name: Cuisine Style, Length: 74225, dtype: object>

In [120]:
restaurants['Price Range'].unique()

array(['$$ - $$$', '$$$$', '$'], dtype=object)

In [121]:
restaurants = restaurants.replace({'$$ - $$$': 'medium', '$': 'low', '$$$$': 'high'})

In [122]:
restaurants[restaurants.Rating == 1.0]

,Unnamed: 0,Name,City,Cuisine Style,Ranking,Rating,Price Range,Number of Reviews,Reviews,URL_TA,ID_TA
13105,7733,Restaurant International 08002 Barcelona,Barcelona,"['Asian', 'Chinese']",7735.0,1.0,medium,43.0,"[['Probably the worst in Barcelona!', 'Food po...",/Restaurant_Review-g187497-d4115730-Reviews-Re...,d4115730
13115,7743,Petipe,Barcelona,['Pizza'],7749.0,1.0,low,2.0,"[[], []]",/Restaurant_Review-g187497-d3382432-Reviews-Pe...,d3382432
13137,7765,Restaurant Noku,Barcelona,['Japanese'],7777.0,1.0,medium,2.0,"[[], []]",/Restaurant_Review-g187497-d8659974-Reviews-Re...,d8659974
13143,7771,Cafe & Te,Barcelona,['Spanish'],7784.0,1.0,medium,3.0,"[[], []]",/Restaurant_Review-g187497-d10504701-Reviews-C...,d10504701
13148,7776,El Rincon De Galicia,Barcelona,"['Spanish', 'Asian']",7790.0,1.0,high,4.0,"[['Ripped off. Dodgy food.'], ['09/16/2017']]",/Restaurant_Review-g187497-d11838894-Reviews-E...,d11838894
24942,3000,la homarderie,Brussels,"['Belgian', 'European']",2999.0,1.0,high,2.0,"[[], []]",/Restaurant_Review-g188644-d1117565-Reviews-La...,d1117565
44780,3687,Made in Correeiros,Lisbon,"['European', 'Portuguese', 'Seafood']",3692.0,1.0,medium,597.0,"[['Very bad restauration', 'Worst experience o...",/Restaurant_Review-g189158-d12714847-Reviews-M...,d12714847
44783,3690,Antao Santos e Martins,Lisbon,"['European', 'Portuguese', 'Seafood']",3695.0,1.0,high,25.0,"[['Useless and a rip-off!', 'Thieving toads'],...",/Restaurant_Review-g189158-d12285117-Reviews-A...,d12285117
44790,3697,Lisboa City,Lisbon,"['European', 'Portuguese']",3704.0,1.0,low,2.0,"[[], []]",/Restaurant_Review-g189158-d8758873-Reviews-Li...,d8758873
44794,3701,Intervalo. Casa Das Comidas,Lisbon,['Mediterranean'],3711.0,1.0,low,2.0,"[['Worst Lunch Ever'], ['04/14/2015']]",/Restaurant_Review-g189158-d3608514-Reviews-In...,d3608514
44798,3705,Li28oa - Wine and Tapas,Lisbon,"['European', 'Portuguese']",3717.0,1.0,medium,2.0,"[['Worst restaurant in town', 'Horrible food']...",/Restaurant_Review-g189158-d13163518-Reviews-L...,d13163518
61871,16291,Domino's Pizza- Crystal Palace,London,['Pizza'],16303.0,1.0,low,8.0,"[['Terrible customer service, my daughter did....",/Restaurant_Review-g186338-d5818787-Reviews-Do...,d5818787
61872,16292,China House,London,"['Asian', 'Chinese']",16304.0,1.0,low,16.0,"[['Incomplete Order...""AVOID,AVOID,AVOID...', ...",/Restaurant_Review-g186338-d7745006-Reviews-Ch...,d7745006
61884,16304,Chop'd CityPoint,London,"['Fast Food', 'Healthy', 'Soups']",16317.0,1.0,low,2.0,"[['Severely disappointing', 'A total joke'], [...",/Restaurant_Review-g186338-d11614999-Reviews-C...,d11614999
61902,16322,Bertorelli - Fetter Lane,London,['Italian'],16337.0,1.0,high,2.0,"[['Went here, had the WORST MEAL ever', 'Do yo...",/Restaurant_Review-g186338-d1421041-Reviews-Be...,d1421041
61930,16350,Tandoor,London,"['Indian', 'Fast Food', 'Asian', 'Middle Easte...",16367.0,1.0,medium,2.0,"[['Take away', 'Terrible tandoor'], ['11/29/20...",/Restaurant_Review-g186338-d11802357-Reviews-T...,d11802357
61954,16374,Bun and Bubble,London,"['Fast Food', 'Asian', 'Korean', 'Street Food'...",16392.0,1.0,medium,2.0,"[['Don’t waste your time or money!', 'Avoid!!!...",/Restaurant_Review-g186338-d11984903-Reviews-B...,d11984903
61963,16383,Selesa Restaurant Hyde Park,London,"['Chinese', 'Indian', 'Asian', 'Malaysian']",16401.0,1.0,high,3.0,"[['Horrible dry meat and processed fake food',...",/Restaurant_Review-g186338-d10744157-Reviews-S...,d10744157
61967,16387,Pizza Hut,London,"['Pizza', 'Fast Food']",16405.0,1.0,low,11.0,"[['Takeaway', ""The worst pizza I've ever order...",/Restaurant_Review-g186338-d8784693-Reviews-Pi...,d8784693
62001,16421,Le Peep Boutique,London,"['French', 'Fusion']",16443.0,1.0,high,6.0,"[['staff party', 'Aqua shard workers party'], ...",/Restaurant_Review-g186338-d7615709-Reviews-Le...,d7615709
76107,8728,Pizzeria Carlos,Madrid,"['Italian', 'Pizza']",8735.0,1.0,medium,2.0,"[[], []]",/Restaurant_Review-g187514-d12239759-Reviews-P...,d12239759
103313,13916,En cas d'encas,Paris,"['American', 'Steakhouse', 'Street Food', 'Kos...",13918.0,1.0,medium,6.0,"[['Bad Service, Inaccurate Food Delivered, St....",/Restaurant_Review-g187147-d10184357-Reviews-E...,d10184357
103328,13931,LINA'S,Paris,['Fast Food'],13935.0,1.0,medium,2.0,"[[], []]",/Restaurant_Review-g187147-d12829902-Reviews-L...,d12829902
103355,13958,EXKi Rambuteau,Paris,"['Belgian', 'European']",13966.0,1.0,medium,2.0,"[[], []]",/Restaurant_Review-g187147-d13313823-Reviews-E...,d13313823
108395,4124,Mystic Cafe,Prague,"['Czech', 'European', 'Central European']",4142.0,1.0,high,255.0,"[['Too many cons', 'High prices'], ['01/05/201...",/Restaurant_Review-g274707-d1230383-Reviews-My...,d1230383
108399,4128,Ristorante Pizzeria Lamberty,Prague,['European'],4146.0,1.0,medium,178.0,"[['Charged £6.80 for half a litre of water', '...",/Restaurant_Review-g274707-d1911017-Reviews-Ri...,d1911017
108400,4129,R & R Cafe,Prague,['Czech'],4147.0,1.0,high,88.0,"[['Avoid at all costs!', 'STAY AWAY AT ALL COS...",/Restaurant_Review-g274707-d1737134-Reviews-R_...,d1737134
108401,4130,Ve Stare Radnici,Prague,"['European', 'Central European', 'Czech']",4148.0,1.0,medium,220.0,"[['No credit cards accepted, extremely high p....",/Restaurant_Review-g274707-d2431998-Reviews-Ve...,d2431998
121217,3433,Pizzeria Arbaillo,Vienna,['Pizza'],3440.0,1.0,low,3.0,"[[], []]",/Restaurant_Review-g190454-d1214556-Reviews-Pi...,d1214556
123639,2131,Atrio,Warsaw,"['Polish', 'European']",2133.0,1.0,low,2.0,"[['The Traveller says NO', ""don't go there""], ...",/Restaurant_Review-g274856-d1628820-Reviews-At...,d1628820
123640,2132,Hummus Bar,Warsaw,"['Middle Eastern', 'Israeli']",2134.0,1.0,low,2.0,"[[""Just don't...""], ['11/20/2016']]",/Restaurant_Review-g274856-d10680290-Reviews-H...,d10680290
123649,2141,Grill Inn,Warsaw,"['Lebanese', 'Mediterranean', 'Turkish']",2150.0,1.0,medium,2.0,"[['Get with the times'], ['09/23/2017']]",/Restaurant_Review-g274856-d11890686-Reviews-G...,d11890686

In [123]:
restaurants_london= restaurants[restaurants.City == 'London']

In [124]:
restaurants_london

,Unnamed: 0,Name,City,Cuisine Style,Ranking,Rating,Price Range,Number of Reviews,Reviews,URL_TA,ID_TA
45580,0,R & H cafe gallery,London,"['Cafe', 'Middle Eastern', 'Persian', 'Vegetar...",1.0,5.0,medium,146.0,"[['Amazing cakes', 'Breakfatst'], ['01/08/2018...",/Restaurant_Review-g186338-d10517849-Reviews-R...,d10517849
45581,1,Osteria Romana,London,"['Italian', 'Mediterranean', 'Vegetarian Frien...",2.0,5.0,high,112.0,[['Small restaurant with the touch of Italian....,/Restaurant_Review-g186338-d13149344-Reviews-O...,d13149344
45582,2,The Oystermen Seafood Bar & Kitchen,London,"['Seafood', 'British', 'Gluten Free Options']",3.0,5.0,medium,255.0,"[['Fantasic!!', 'Superb Food, Warm and Welcomi...",/Restaurant_Review-g186338-d12518072-Reviews-T...,d12518072
45583,3,Liman Restaurant,London,"['Mediterranean', 'European', 'Turkish', 'Midd...",4.0,5.0,medium,945.0,"[['A good experience', 'Excellent Establishmen...",/Restaurant_Review-g186338-d10444968-Reviews-L...,d10444968
45584,4,Holy Smoke,London,"['International', 'Vegetarian Friendly', 'Glut...",5.0,5.0,medium,433.0,"[['Always consistently good food and service',...",/Restaurant_Review-g186338-d7697088-Reviews-Ho...,d7697088
...,...,...,...,...,...,...,...,...,...,...,...
61930,16350,Tandoor,London,"['Indian', 'Fast Food', 'Asian', 'Middle Easte...",16367.0,1.0,medium,2.0,"[['Take away', 'Terrible tandoor'], ['11/29/20...",/Restaurant_Review-g186338-d11802357-Reviews-T...,d11802357
61954,16374,Bun and Bubble,London,"['Fast Food', 'Asian', 'Korean', 'Street Food'...",16392.0,1.0,medium,2.0,"[['Don’t waste your time or money!', 'Avoid!!!...",/Restaurant_Review-g186338-d11984903-Reviews-B...,d11984903
61963,16383,Selesa Restaurant Hyde Park,London,"['Chinese', 'Indian', 'Asian', 'Malaysian']",16401.0,1.0,high,3.0,"[['Horrible dry meat and processed fake food',...",/Restaurant_Review-g186338-d10744157-Reviews-S...,d10744157
61967,16387,Pizza Hut,London,"['Pizza', 'Fast Food']",16405.0,1.0,low,11.0,"[['Takeaway', ""The worst pizza I've ever order...",/Restaurant_Review-g186338-d8784693-Reviews-Pi...,d8784693
62001,16421,Le Peep Boutique,London,"['French', 'Fusion']",16443.0,1.0,high,6.0,"[['staff party', 'Aqua shard workers party'], ...",/Restaurant_Review-g186338-d7615709-Reviews-Le...,d7615709

In [125]:
restaurants.drop(['Unnamed: 0'] ,axis=1, inplace=True)

In [126]:
restaurants.to_json("../data/restaurants_json", orient="records")

In [127]:
from pymongo import MongoClient

In [128]:
conn = MongoClient("localhost:27017")

In [129]:
conn.list_database_names()

['HP', 'RickAndMorty', 'admin', 'config', 'ironhack', 'local', 'project_final']

In [130]:
db = conn.get_database("project_final")

In [131]:
db.list_collection_names()

['restaurants']

In [132]:
collection = db.get_collection("restaurants")

In [133]:
collection.find_one()

{'_id': ObjectId('5fd29dce86cc4c64e0897909'),
 'Name': 'Blue Pepper Restaurant And Candlelight Cruises',
 'City': 'Amsterdam',
 'Cuisine Style': "['Asian', 'Indonesian', 'Vegetarian Friendly', 'Vegan Options', 'Gluten Free Options']",
 'Ranking': 8.0,
 'Rating': 4.5,
 'Price Range': 'high',
 'Number of Reviews': 675.0,
 'Reviews': "[['Great Experience', 'A true delight'], ['01/08/2018', '01/07/2018']]",
 'URL_TA': '/Restaurant_Review-g188590-d697058-Reviews-Blue_Pepper_Restaurant_And_Candlelight_Cruises-Amsterdam_North_Holland_Province.html',
 'ID_TA': 'd697058'}

In [134]:
restaurants_madrid.sample(20)

,Unnamed: 0,Name,City,Cuisine Style,Ranking,Rating,Price Range,Number of Reviews,Reviews,URL_TA,ID_TA
72755,5376,Landania,Madrid,['European'],5379.0,3.5,medium,77.0,"[['Nice atmosphere', 'nice atmosphere and food...",/Restaurant_Review-g187514-d1990880-Reviews-La...,d1990880
69346,1967,De la Riva,Madrid,"['Mediterranean', 'Spanish']",1969.0,4.0,medium,156.0,[['A truly superb neighborhood restaurant. On....,/Restaurant_Review-g187514-d1059372-Reviews-De...,d1059372
68101,722,La Catedral,Madrid,"['Mediterranean', 'European', 'Spanish', 'Vege...",723.0,3.5,medium,749.0,"[['Gorgeous Decor and Great Food!', 'picturesq...",/Restaurant_Review-g187514-d1594131-Reviews-La...,d1594131
69528,2149,Cerveceria Asador El Trillo,Madrid,"['Vegetarian Friendly', 'Gluten Free Options']",2151.0,3.5,medium,162.0,"[['Fantastic weekend menu!!!!!', 'Disaster'], ...",/Restaurant_Review-g187514-d6657028-Reviews-Ce...,d6657028
70629,3250,Las Bravas,Madrid,"['Fast Food', 'Spanish']",3252.0,3.5,low,238.0,"[['Good food and friendly staff', 'Okay bravas...",/Restaurant_Review-g187514-d2479947-Reviews-La...,d2479947
68041,662,Bodegas Rosell,Madrid,"['Bar', 'Mediterranean', 'Spanish', 'Wine Bar'...",663.0,4.0,medium,530.0,"[['A place to try Spanish cuisine', 'Good sele...",/Restaurant_Review-g187514-d844414-Reviews-Bod...,d844414
68829,1450,Restaurante Hermanos Egea,Madrid,"['Mediterranean', 'Spanish']",1452.0,4.5,medium,41.0,"[[], []]",/Restaurant_Review-g187514-d7303748-Reviews-Re...,d7303748
67959,580,Tommy Mel's,Madrid,"['American', 'Fast Food', 'Diner', 'Central Am...",581.0,4.0,medium,410.0,"[['Overall good', 'Nice fastfood restaurant'],...",/Restaurant_Review-g187514-d7014127-Reviews-To...,d7014127
67878,499,La Venencia,Madrid,"['Spanish', 'Wine Bar']",500.0,4.5,low,286.0,"[['Old World Madrid', 'Nice place to stay'], [...",/Restaurant_Review-g187514-d717308-Reviews-La_...,d717308
74197,6818,Wagamama Genova,Madrid,"['Mediterranean', 'Vegetarian Friendly']",6821.0,3.0,medium,63.0,"[['Quick lunch on the go', 'Dinner'], ['09/16/...",/Restaurant_Review-g187514-d12550985-Reviews-W...,d12550985
69873,2494,Asador del Norte,Madrid,['Spanish'],2496.0,4.0,medium,35.0,"[['Good local restaurant'], ['03/04/2017']]",/Restaurant_Review-g187514-d4603386-Reviews-As...,d4603386
71861,4482,Banzai Sushi Bar,Madrid,"['Japanese', 'Sushi']",4484.0,3.5,medium,179.0,"[['Real and tasty japaneese food', 'Wanted thi...",/Restaurant_Review-g187514-d1765594-Reviews-Ba...,d1765594
74820,7441,La Bodega Madrid,Madrid,"['Cafe', 'Spanish']",7447.0,2.5,low,12.0,"[['Not good', 'Not nice at all'], ['04/06/2017...",/Restaurant_Review-g187514-d4827503-Reviews-La...,d4827503
68351,972,Distrito Vegano,Madrid,"['Spanish', 'Vegetarian Friendly', 'Vegan Opti...",973.0,4.0,medium,102.0,"[['Tasty, nice, quick', 'Great little place wi...",/Restaurant_Review-g187514-d10588044-Reviews-D...,d10588044
68397,1018,Bar Postas,Madrid,"['Bar', 'Fast Food', 'Mediterranean', 'Spanish']",1019.0,4.0,low,210.0,"[['Cheap and good!!', 'No frills bar, best sel...",/Restaurant_Review-g187514-d6404683-Reviews-Ba...,d6404683
72678,5299,Restaurante Fortuny,Madrid,"['European', 'Mediterranean', 'Spanish', 'Vege...",5302.0,3.5,medium,214.0,"[['Dinner & Nightclub to visit', 'Cool club'],...",/Restaurant_Review-g187514-d991837-Reviews-Res...,d991837
69706,2327,Casa Ananias Restaurant,Madrid,['Spanish'],2329.0,4.0,medium,75.0,"[['Great family restaurant', 'The restaurant I...",/Restaurant_Review-g187514-d4071963-Reviews-Ca...,d4071963
67450,71,La Pizzateca,Madrid,"['Italian', 'Pizza', 'Fast Food', 'Mediterrane...",72.0,4.5,low,729.0,"[['Good food', 'Very tasty pizza'], ['11/27/20...",/Restaurant_Review-g187514-d2086638-Reviews-La...,d2086638
75528,8149,Cafe And Te Arenal 9,Madrid,['Spanish'],8156.0,2.5,medium,13.0,"[['Paella Valenciana', 'Average food, unfriend...",/Restaurant_Review-g187514-d10517559-Reviews-C...,d10517559
72951,5572,Patatas fritas La Azucena,Madrid,['Mediterranean'],5575.0,5.0,medium,9.0,"[[], []]",/Restaurant_Review-g187514-d8606418-Reviews-Pa...,d8606418

In [147]:
coordenadas = pd.read_csv('../data/dataframefinal.csv')